services:
  buss:
    container_name: buss
    network_mode: host
    restart: unless-stopped
    build:
      context: .
    env_file: ".env"
    volumes:
      - /home/sergey/docker/buss/index.js:/app/index.js
      - /home/sergey/docker/buss/public:/app/public
